// <auto-generated />
using System;
using AssetManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetManagementSystem.Migrations
{
    [DbContext(typeof(AssetDbContext))]
    [Migration("20260115221247_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetManagementSystem.Models.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetId"));

                    b.Property<string>("AssetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssetId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            AssetId = 1,
                            AssetName = "Dell Laptop",
                            AssetType = "Laptop",
                            Price = 60000m,
                            PurchaseDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "DL-001",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 2,
                            AssetName = "HP Laptop",
                            AssetType = "Laptop",
                            Price = 58000m,
                            PurchaseDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "HP-002",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 3,
                            AssetName = "Lenovo Laptop",
                            AssetType = "Laptop",
                            Price = 62000m,
                            PurchaseDate = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "LN-003",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 4,
                            AssetName = "MacBook Air",
                            AssetType = "Laptop",
                            Price = 95000m,
                            PurchaseDate = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "MB-004",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 5,
                            AssetName = "Dell Monitor",
                            AssetType = "Monitor",
                            Price = 15000m,
                            PurchaseDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "DM-005",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 6,
                            AssetName = "HP Monitor",
                            AssetType = "Monitor",
                            Price = 14000m,
                            PurchaseDate = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "HM-006",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 7,
                            AssetName = "Logitech Mouse",
                            AssetType = "Mouse",
                            Price = 1200m,
                            PurchaseDate = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "LM-007",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 8,
                            AssetName = "Dell Keyboard",
                            AssetType = "Keyboard",
                            Price = 1800m,
                            PurchaseDate = new DateTime(2023, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "DK-008",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 9,
                            AssetName = "iPhone",
                            AssetType = "Mobile",
                            Price = 75000m,
                            PurchaseDate = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "IP-009",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 10,
                            AssetName = "Samsung Phone",
                            AssetType = "Mobile",
                            Price = 42000m,
                            PurchaseDate = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SP-010",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 11,
                            AssetName = "Acer Laptop",
                            AssetType = "Laptop",
                            Price = 55000m,
                            PurchaseDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "AC-011",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 12,
                            AssetName = "Asus Laptop",
                            AssetType = "Laptop",
                            Price = 60000m,
                            PurchaseDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "AS-012",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 13,
                            AssetName = "LG Monitor",
                            AssetType = "Monitor",
                            Price = 16000m,
                            PurchaseDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "LG-013",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 14,
                            AssetName = "Wireless Keyboard",
                            AssetType = "Keyboard",
                            Price = 2200m,
                            PurchaseDate = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "WK-014",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 15,
                            AssetName = "Wireless Mouse",
                            AssetType = "Mouse",
                            Price = 1500m,
                            PurchaseDate = new DateTime(2023, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "WM-015",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 16,
                            AssetName = "iPad",
                            AssetType = "Tablet",
                            Price = 50000m,
                            PurchaseDate = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "IP-016",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 17,
                            AssetName = "Samsung Tablet",
                            AssetType = "Tablet",
                            Price = 42000m,
                            PurchaseDate = new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "ST-017",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 18,
                            AssetName = "HP Printer",
                            AssetType = "Printer",
                            Price = 18000m,
                            PurchaseDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "HP-018",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 19,
                            AssetName = "Canon Printer",
                            AssetType = "Printer",
                            Price = 20000m,
                            PurchaseDate = new DateTime(2023, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "CP-019",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 20,
                            AssetName = "Projector",
                            AssetType = "Projector",
                            Price = 55000m,
                            PurchaseDate = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "PJ-020",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 21,
                            AssetName = "Router",
                            AssetType = "Network",
                            Price = 8000m,
                            PurchaseDate = new DateTime(2023, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "RT-021",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 22,
                            AssetName = "Switch",
                            AssetType = "Network",
                            Price = 12000m,
                            PurchaseDate = new DateTime(2023, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SW-022",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 23,
                            AssetName = "External HDD",
                            AssetType = "Storage",
                            Price = 7000m,
                            PurchaseDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "HD-023",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 24,
                            AssetName = "SSD Drive",
                            AssetType = "Storage",
                            Price = 9000m,
                            PurchaseDate = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SD-024",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 25,
                            AssetName = "Webcam",
                            AssetType = "Camera",
                            Price = 4000m,
                            PurchaseDate = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "WC-025",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 26,
                            AssetName = "Headset",
                            AssetType = "Audio",
                            Price = 3500m,
                            PurchaseDate = new DateTime(2023, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "HS-026",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 27,
                            AssetName = "Speakers",
                            AssetType = "Audio",
                            Price = 4500m,
                            PurchaseDate = new DateTime(2023, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SP-027",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 28,
                            AssetName = "UPS",
                            AssetType = "Power",
                            Price = 11000m,
                            PurchaseDate = new DateTime(2023, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "UP-028",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 29,
                            AssetName = "Scanner",
                            AssetType = "Scanner",
                            Price = 13000m,
                            PurchaseDate = new DateTime(2023, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SC-029",
                            Status = "Unassigned"
                        },
                        new
                        {
                            AssetId = 30,
                            AssetName = "Biometric Device",
                            AssetType = "Security",
                            Price = 9000m,
                            PurchaseDate = new DateTime(2023, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "BD-030",
                            Status = "Unassigned"
                        });
                });

            modelBuilder.Entity("AssetManagementSystem.Models.AssetAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("AssignmentId");

                    b.ToTable("AssetAssignments");
                });

            modelBuilder.Entity("AssetManagementSystem.Models.AssetHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("HistoryId");

                    b.ToTable("AssetHistories");
                });

            modelBuilder.Entity("AssetManagementSystem.Models.AssetRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("AssetType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestId");

                    b.ToTable("AssetRequests");
                });

            modelBuilder.Entity("AssetManagementSystem.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Department = "IT",
                            Email = "tushar@pratiti.com",
                            Name = "Tushar Bhosale"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Department = "HR",
                            Email = "rahul@company.com",
                            Name = "Amit Verma"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Department = "Finance",
                            Email = "sneha@company.com",
                            Name = "Sneha Patil"
                        },
                        new
                        {
                            EmployeeId = 4,
                            Department = "Admin",
                            Email = "pooja@company.com",
                            Name = "Pooja Singh"
                        },
                        new
                        {
                            EmployeeId = 5,
                            Department = "IT",
                            Email = "ankit@company.com",
                            Name = "Ankit Jain"
                        },
                        new
                        {
                            EmployeeId = 6,
                            Department = "HR",
                            Email = "neha@company.com",
                            Name = "Neha Kulkarni"
                        },
                        new
                        {
                            EmployeeId = 7,
                            Department = "Support",
                            Email = "rohit@company.com",
                            Name = "Rohit Mehta"
                        },
                        new
                        {
                            EmployeeId = 8,
                            Department = "Finance",
                            Email = "kiran@company.com",
                            Name = "Kiran Deshpande"
                        },
                        new
                        {
                            EmployeeId = 9,
                            Department = "IT",
                            Email = "suresh@company.com",
                            Name = "Suresh Iyer"
                        },
                        new
                        {
                            EmployeeId = 10,
                            Department = "HR",
                            Email = "priya@company.com",
                            Name = "Priya Nair"
                        },
                        new
                        {
                            EmployeeId = 11,
                            Department = "Admin",
                            Email = "vikas@company.com",
                            Name = "Vikas Gupta"
                        },
                        new
                        {
                            EmployeeId = 12,
                            Department = "Support",
                            Email = "manoj@company.com",
                            Name = "Manoj Pawar"
                        },
                        new
                        {
                            EmployeeId = 13,
                            Department = "Finance",
                            Email = "aarti@company.com",
                            Name = "Aarti Joshi"
                        },
                        new
                        {
                            EmployeeId = 14,
                            Department = "IT",
                            Email = "deepak@company.com",
                            Name = "Deepak Rao"
                        },
                        new
                        {
                            EmployeeId = 15,
                            Department = "HR",
                            Email = "nikhil@company.com",
                            Name = "Nikhil Patil"
                        },
                        new
                        {
                            EmployeeId = 16,
                            Department = "IT",
                            Email = "riya@company.com",
                            Name = "Riya Kulkarni"
                        },
                        new
                        {
                            EmployeeId = 17,
                            Department = "Finance",
                            Email = "aditya@company.com",
                            Name = "Aditya Joshi"
                        },
                        new
                        {
                            EmployeeId = 18,
                            Department = "HR",
                            Email = "meenal@company.com",
                            Name = "Meenal Desai"
                        },
                        new
                        {
                            EmployeeId = 19,
                            Department = "Support",
                            Email = "sanket@company.com",
                            Name = "Sanket Patil"
                        },
                        new
                        {
                            EmployeeId = 20,
                            Department = "Admin",
                            Email = "rohini@company.com",
                            Name = "Rohini Shah"
                        });
                });

            modelBuilder.Entity("AssetManagementSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Password = "admin123",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            EmployeeId = 1,
                            Password = "tushar123",
                            Role = "Employee",
                            Username = "tushar"
                        },
                        new
                        {
                            UserId = 3,
                            EmployeeId = 2,
                            Password = "amit123",
                            Role = "Employee",
                            Username = "amit"
                        },
                        new
                        {
                            UserId = 4,
                            EmployeeId = 3,
                            Password = "sneha123",
                            Role = "Employee",
                            Username = "sneha"
                        },
                        new
                        {
                            UserId = 5,
                            EmployeeId = 4,
                            Password = "pooja123",
                            Role = "Employee",
                            Username = "pooja"
                        },
                        new
                        {
                            UserId = 6,
                            EmployeeId = 5,
                            Password = "ankit123",
                            Role = "Employee",
                            Username = "ankit"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
